### ISSUE TITLE
Edge-processor cannot recognize two cameras when booted up with emmc

### ISSUE THREAD

**Issue by seonghapark** [waggle-sensor/core#6]
Edge-processor could not recognize two cameras logically when booted up with recovered emmc. As two hardware of cameras, XU4 recognized, but no new video device in /dev nor waggle_cam created. After recovery of sd card with the emmc and boot up with the sd card, it got the same problem.

**Comment by seonghapark** [comment]
--> (maybe) temporal solution:
I removed
--exclude='media/*' in waggle_init.sh when it does rsync. Then it solves the problem.

**Comment by seonghapark** [comment]
--> remove --exclude='media/*' in waggle_init.sh
it seems a solution for this issue.

**Comment by gemblerz** [comment]
The issue is moved to proper location. Closed.
